#!/bin/bash

export LANG=en_CA.UTF-8

if [ x$R == x ]; then R=R; fi

for R_estim in proxyW proxyWXo-filter proxyWXss-filter \
               proxyDss-filter proxyDn proxyEn proxyEn-daily
do
  for R_est_type in Rt Ru Ru_smoothed; do
    $R --save --no-restore --args $R_estim $R_est_type \
       <R-model.R >&R-model-$R_estim-$R_est_type.out
    # cp .RData R-model-$R_estim-$R_est_type.RData
  done
done

for R_estim in proxyW
do
  for R_est_type in Ru_smoothed; do
    $R --save --no-restore --args $R_estim $R_est_type e2 \
       <R-model.R >&R-model-$R_estim-$R_est_type-e2.out
    # cp .RData R-model-$R_estim-$R_est_type-e2.RData
    $R --save --no-restore --args $R_estim $R_est_type e3 \
       <R-model.R >&R-model-$R_estim-$R_est_type-e3.out
    # cp .RData R-model-$R_estim-$R_est_type-e3.RData
  done
done
