#!/bin/bash

export LANG=en_CA.UTF-8

if [ x$R == x ]; then R=R; fi

for R_estim in proxyW proxyWXo-filter proxyWXss-filter \
               proxyDss-filter proxyDn-filter
do
  for R_est_type in Rt Ru Ru_smoothed; do
    $R --save --no-restore --args $R_estim $R_est_type \
       <R-model.R >&R-model-$R_estim-$R_est_type.out
    # cp .RData R-model-$R_estim-$R_est_type.RData
  done
done

