#!/bin/bash

# Search for optimal immunity decay rates for i3 immunity model, for each 
# of the coronaviruses, using options s2 and e3.

R_estim=proxyDss-filter  # proxies to use
R_est_type=Rt            # R estimate to use

export LANG=en_CA.UTF-8

if [ x$R == x ]; then R=R; fi

( for NL63 in 0.91 0.92; do
    for E229 in 0.91 0.92; do
      for NL63ltd in 0.93 0.94; do
        for E229ltd in 0.93 0.94; do
          for NL63ltf in 0.0019 0.0020; do
            for E229ltf in 0.0019 0.0020; do
              echo -n \
               `$R --no-save --no-restore \
                   --args $R_estim $R_est_type nosim s2 i3 e3 \
                          decay:NL63=$NL63,E229=$E229 \
                          ltdecay:NL63=$NL63ltd,E229=$E229ltd \
                          ltfactor:NL63=$NL63ltf,E229=$E229ltf \
                   <R-model.R | fgrep "Residual standard error" \
                              | sed "s/.*://" | sed "s/ on .*//" | head -1`
              echo " " decay:NL63=$NL63,E229=$E229 \
                       ltdecay:NL63=$NL63ltd,E229=$E229ltd \
                       ltfactor:NL63=$NL63ltf,E229=$E229ltf
            done
          done
        done
      done
    done
  done
) >search-lt2.grp1

sort -n <search-lt2.grp1 | head -1

( for OC43 in 0.78 0.80; do
    for HKU1 in 0.70 0.75; do
      for OC43ltd in 0.985 0.99; do
        for HKU1ltd in 0.975 0.98; do
          for OC43ltf in 0.0019 0.0020; do
            for HKU1ltf in 0.0019 0.0020; do
              echo -n \
               `$R --no-save --no-restore \
                   --args $R_estim $R_est_type nosim s2 i3 e3 \
                          decay:OC43=$OC43,HKU1=$HKU1 \
                          ltdecay:OC43=$OC43ltd,HKU1=$HKU1ltd \
                          ltfactor:OC43=$OC43ltf,HKU1=$HKU1ltf \
                   <R-model.R | fgrep "Residual standard error" \
                              | sed "s/.*://" | sed "s/ on .*//" | tail -1`
              echo " " decay:OC43=$OC43,HKU1=$HKU1 \
                       ltdecay:OC43=$OC43ltd,HKU1=$HKU1ltd \
                       ltfactor:OC43=$OC43ltf,HKU1=$HKU1ltf
            done
          done
        done
      done
    done
  done
) >search-lt2.grp2

sort -n <search-lt2.grp2 | head -1
