#!/bin/bash

export LANG=en_CA.UTF-8

if [ x$R == x ]; then R=R; fi

for proxy in proxyW proxyA proxyB proxyC proxyD proxyWX proxyAX \
             proxyWo proxyAo proxyBo proxyCo proxyDo proxyWXo proxyAXo \
             proxyWss proxyAss proxyBss proxyCss proxyDss proxyWXss proxyAXss \
             proxyWm proxyAm proxyBm proxyCm proxyDm \
             proxyWn proxyAn proxyBn proxyCn proxyDn \
#            proxyWs proxyAs proxyBs proxyCs proxyDs
do
  $R --save --no-restore \
     --args $proxy $method <R-est.R >&R-est-$proxy.out
  # cp .RData R-est-$proxy.RData
  $R --save --no-restore \
     --args $proxy $method filter <R-est.R >&R-est-$proxy-filter.out
  # cp .RData R-est-$proxy-filter.RData
done
