#!/bin/bash

export LANG=en_CA.UTF-8

if [ x$R == x ]; then R=R; fi

for proxy in proxyW proxyA proxyB proxyC proxyD proxyE proxyWX proxyAX \
             proxyWo proxyAo proxyBo proxyCo proxyDo proxyEo proxyWXo proxyAXo \
             proxyCs proxyDs proxyEs proxyWXs proxyAXs \
             proxyCss proxyDss proxyEss proxyWXss proxyAXss \
             proxyCm proxyDm proxyEm proxyWXm proxyAXm \
             proxyCn proxyDn proxyEn proxyWXn proxyAXn
do
  $R --save --no-restore \
     --args $proxy $method <R-est.R >&R-est-$proxy.out
  # cp .RData R-est-$proxy.RData
  $R --save --no-restore \
     --args $proxy $method filter <R-est.R >&R-est-$proxy-filter.out
  # cp .RData R-est-$proxy-filter.RData
done
