#!/bin/bash

export LANG=en_CA.UTF-8

if [ x$R == x ]; then R=R; fi

for proxy in proxyW proxyA proxyB proxyC proxyD proxyWX proxyAX \
             proxyWo proxyAo proxyBo proxyCo proxyDo proxyWXo proxyAXo \
             proxyCs proxyDs proxyWXs proxyAXs \
             proxyCss proxyDss proxyWXss proxyAXss \
             proxyCm proxyDm proxyWXm proxyAXm \
             proxyCn proxyDn proxyWXn proxyAXn
do
  $R --save --no-restore \
     --args $proxy $method <R-est.R >&R-est-$proxy.out
  # cp .RData R-est-$proxy.RData
  $R --save --no-restore \
     --args $proxy $method filter <R-est.R >&R-est-$proxy-filter.out
  # cp .RData R-est-$proxy-filter.RData
done
