#!/bin/bash

export LANG=en_CA.UTF-8

if [ x$R == x ]; then R=pqR; fi

$R --no-save --no-restore --args proxyEn-daily i6 e3 sqrt opt:$1 \
       save:$2 init:$3 errorsd:$4 offsetsd:0.1 fix_err_alpha \
       <reg-sim.R >&reg-sim-proxyEn-daily-i6-e3-sqrt-$2.out

git show | head -1 >> reg-sim-proxyEn-daily-i6-e3-sqrt-$2.out
git diff HEAD >> reg-sim-proxyEn-daily-i6-e3-sqrt-$2.out
